name: e2e testing

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'src/*'
      - package.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
      - name: Install package
        run: yarn
      - name: Run API in background
        run: |
          yarn build
          node dist/main > .log &
          echo $! > .pid
        env:
          SERVICE_HOST: 0.0.0.0
          SERVICE_PORT: 3000
      - name: Healthcheck API
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://localhost:3000/healthz
          max-attempts: 10
          retry-delay: 5s
          retry-all: false
      - name: Run test
        run: yarn test:e2e
        env:
          API_URL: http://localhost:3000
      - name: Show Log
        if: failure()
        run: cat .log
      - name: Kill API
        run: kill $(cat .pid)
        if: always()
