name: 📀

on:
  release:
    types: [published]
env:
  SERVICE_NAME: dnd-ci-cd # TODO: Change this to your service name
  RELEASE_VERSION: latest
jobs:
  image:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOC_USERNAME }}
          password: ${{ secrets.DOC_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/${{ secrets.DOC_PROJECT_NAME }}/${{ env.SERVICE_NAME }}:${{ env.RELEASE_VERSION }}
          build-args: |
            "SERVICE_VERSION=${{ env.RELEASE_VERSION }}"
          secrets: |
            "token=${{ secrets.PAT }}"
          secret-files: |
            "npmrc=${{ env.NPM_CONFIG_USERCONFIG }}"

      - name: Deploy to Kubernetes
        uses: deliverybot/kubectl@v1
        with:
          args: apply -f k8s
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
