name: Validate Linter

on:
  push:
    branches:
      - '**'
      - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
      - name: Install package
        run: yarn
      - name: Check lint
        run: yarn lint
      - name: Run test
        run: yarn test
